# Generated by Django 5.0.8 on 2024-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'option1', 'option2'), name='unique_match_per_round'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'option2', 'option1'), name='unique_reverse_match_per_round'),
        ),
    ]
