# Generated by Django x.x.x on YYYY-MM-DD
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_match_unique_match_per_round_and_more'),
    ]

    operations = [
        # Commenter ou supprimer cette ligne si elle pose problème
        # migrations.RemoveField(
        #     model_name='tournament',
        #     name='creator',
        # ),
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
