# Generated by Django 5.1.4 on 2024-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_tournament_creator_alter_round_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='creator',
        ),
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
